schema_version = "1.0.0"

version = "2.0.0"
blender_version_min = "4.2.0"

id = "io_scene_pyrogenesis"
name = "Blender Pyrogenesis Importer"
tagline = "Import Pyrogenesis Actors into Blender"
maintainer = "Stanislas Daniel Claude Dolcini <stanislas.dolcini@devinci.fr>"
type = "add-on"
website = "https://github.com/StanleySweet/blender_pyrogenesis_importer"
tags = ["Import-Export"]
license = ["SPDX:GPL-2.0-or-later"]
copyright = [
    "2024 seragh",
    "2024 Stanislas Daniel Claude Dolcini",
]

[permissions]
files = "Fixup Maya/3DS dae and import pyrogenesis actor (.xml) from disk"
